services:
  app:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    volumes:
      - ./backend:/backend
    ports:
      - "${EXPOSE_APP_PORT}:8080"
    environment:
      - FLASK_ENV=${FLASK_ENV}
      - DATABASE_URL=${DATABASE_URL}
    depends_on:
      - db

  db:
    image: mysql:8.0
    ports:
      - "${EXPOSE_DATABASE_PORT}:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=${DATABASE_ROOT_PASSWORD}
      - MYSQL_DATABASE=${DATABASE_NAME}
      - MYSQL_USER=${DATABASE_USER}
      - MYSQL_PASSWORD=${DATABASE_PASSWORD}
    volumes:
      - python_app_data:/var/lib/mysql

volumes:
  python_app_data:
