services:
  app:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    volumes:
      - ./backend:/backend
    networks:
      - python-app-backend-network
    ports:
      - "${EXPOSE_APP_PORT}:8080"
    environment:
      - FLASK_ENV=${FLASK_ENV}
      - DATABASE_URL=${DATABASE_URL}
    depends_on:
      - db

  db:
    image: mysql:8.0
    networks:
      - python-app-backend-network
    ports:
      - "${EXPOSE_DATABASE_PORT}:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=${DATABASE_ROOT_PASSWORD}
      - MYSQL_DATABASE=${DATABASE_NAME}
      - MYSQL_USER=${DATABASE_USER}
      - MYSQL_PASSWORD=${DATABASE_PASSWORD}
    volumes:
      - python-app-backend-data:/var/lib/mysql

networks:
  python-app-backend-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.33.3.0/24

volumes:
  python-app-backend-data:
